### ISSUE TITLE
Rebuild rmm 22.08.0 with CUDA Python 11.7.0?

### ISSUE THREAD

**Issue by leofang** [conda-forge/rmm-feedstock#15]
This is needed due to the ABI breaking in CUDA Python 11.7.1 (https://github.com/conda-forge/cuda-python-feedstock/issues/15). Open for discussion.

**Comment by kkraus14** [comment]
Regardless of whether we rebuild or not, we should do a repodata patch for the current packages so that users don't end up with broken environments.

**Comment by leofang** [comment]
@kkraus14 Yes that's right. But, remind me as I don't remember if the repodata records the package versions used at the build-time? We can certainly patch the runtime dependencies, run_exports, etc, but how do we know from repodata what packages need this patch, other than doing it case by case?

**Comment by leofang** [comment]
Repodata is patched in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/325.
